### ISSUE TITLE
Integration in Angular failing to import flattenChildren()

### ISSUE THREAD

**Issue by wlievens** [silx-kit/h5web#914] opened 2021-12-30 22:25 UTC
### Describe the bug

I'm attempting to integrate the component in an Angular application.
This is partially successful, I made an Angular wrapper component where I instantiate the h5web component as follows:

```
ReactDOM.render(
  React.createElement(H5GroveProvider, {
    url: url,
    filepath: '',
    children: React.createElement(App, {
      startFullscreen: false
    })
  }),
  document.getElementById(this.rootId)
);
```

My backend is h5grove compatible at the URL where I am testing it. I can browse the HDF5 tree just fine and can see metadata, attributes, and scalar values.

However, when I click a multidimensional dataset node, I get the following error:

```react_keyed_flatten_children__WEBPACK_IMPORTED_MODULE_5__ is not a function```

I traced this to the following line in the `Toolbar` function/class and checked with some console prints, and it indeed isn't a function ... it's the `react-keyed-flatten-children` module object being referred at the following line:

```const allChildren = flattenChildren(children).filter(isReactElement);```

If I replace that line with:

```const allChildren = flattenChildren.default(children).filter(isReactElement);```

everything works fine! So somehow it is failing to recognise the **default export** on `flattenChildren` when I integrate the component in Angular.

Now, I don't know much about TypeScript and JavaScript's import magic, so I tried various combinations of setting the tsconfig values for `esModuleInterop`, `allowSyntheticDefaultImports`, `isolatedModules` and so forth but to no avail.

### To Reproduce

I'm not sure anyone is interested in debugging my Angular setup since this is a React component so I was hoping for some wisdom from above regarding the peculiarities of TypeScript and/or JavaScript's import behaviour. If that leads us nowhere I can always try setting up a clean Angular sample app.

### Expected behaviour

No errors on a trivial function import.

### Screenshots

![image](https://user-images.githubusercontent.com/1073326/147791790-cc7bc9fc-b555-4ea8-95da-d66a125b53ae.png)

### Context

- OS: Windows
- Browser: Chrome
- Version: 1.3.0
- H5Web context: @h5web/lib, @h5web/app

**Comment by wlievens** [comment] 2022-01-03 10:27
This issue seems related, however I don't know what role webpack plays in the whole setup

https://github.com/webpack/webpack/issues/12675

**Comment by axelboc** [comment] 2022-01-06 10:42
Hey, thanks for the report! This is very enigmatic. Fortunately, we've done a round of dependency upgrades a few weeks ago in #897, _after_ the latest v1.3.0 release. So before going further, I'd recommend waiting for the next release to see if the error disappears. We'll try to do the release asap, hopefully next week.

**Comment by wlievens** [comment] 2022-01-06 15:01
Thanks for the feedback. To add some more information: I tried an alternate setup where I made a small pure react app (with **create-react-app** cli) setting up just h5web, and I'm getting exactly the same issue.

Hopefully your new release helps out!

**Comment by wlievens** [comment] 2022-01-12 13:58
Hey, is there any information on the schedule for the upcoming release? Thanks in advance!

**Comment by axelboc** [comment] 2022-01-12 14:25
Should be this afternoon or tomorrow. 😉

**Comment by wlievens** [comment] 2022-01-12 14:28
Perfect, thanks

**Comment by loichuder** [comment] 2022-01-13 10:02
[v1.4.0](https://github.com/silx-kit/h5web/releases/tag/v1.4.0) landed this morning. 

You can give it a try and tell us if it fixes your issue :slightly_smiling_face:

**Comment by wlievens** [comment] 2022-01-13 10:25
Unfortunately, the error persists:

![image](https://user-images.githubusercontent.com/1073326/149312413-2536c992-58c0-407f-b23a-b692ba151863.png)

To confirm that I am using the latest version:

![image](https://user-images.githubusercontent.com/1073326/149312537-1a0db5f0-a308-4fbf-8d0b-e747b965e238.png)

**Comment by axelboc** [comment] 2022-01-13 10:35
Hmm sorry to hear that. Do you use `npm` or `yarn` as your package manager? We use `pnpm` in our projects, which may explain why we hadn't encountered this error so far.

**Comment by wlievens** [comment] 2022-01-13 10:50
I use plain NPM. Maybe you can try making a small project where you import just h5web in a plain NPM setup?

**Comment by axelboc** [comment] 2022-01-13 10:57
Yep, I'm on it 😉 

Got stuck for a sec on trying to create a new CRA app with v4.0.3 (they've released v5 recently, which we haven't tested yet). This is the magic command, FYI: `npx create-react-app --scripts-version 4.0.3 my-app`

**Comment by axelboc** [comment] 2022-01-13 11:06
So here is what I've done and it seems to work (with `node@16.4.0` and `npm@7.19.0`):

```bash
$ npx create-react-app --scripts-version 4.0.3 my-app
$ cd my-app
$ npm install --save @h5web/app
```

In `App.js`:

```jsx
import "@h5web/app/dist/style-lib.css";
import "@h5web/app/dist/style.css";

import React from "react";
import { App, MockProvider } from "@h5web/app";

function MyApp() {
  return (
    <div style={{ height: "100vh" }}>
      <MockProvider>
        <App />
      </MockProvider>
    </div>
  );
}

export default MyApp;
```

```bash
npm start
```

![image](https://user-images.githubusercontent.com/2936402/149318582-8393b7ed-08ac-49b5-9826-d7222c2d3347.png)

**Comment by wlievens** [comment] 2022-01-13 11:45
Your example works on my end. And if I replace the MockProvider with a H5GroveProvider pointing to my backend URL, it also works. Guess I have to find out where I'm doing things differently now in my other experiments... :-)

**Comment by wlievens** [comment] 2022-01-13 12:44
Ah, some progress! Thanks to your hint I noticed that my experimental application (outside of the actual react project) was using **react-scripts 5**. Reverting to v4 fixes the issue.

I'm trying to force the same changes now on my main application but I haven't gotten it fixed just yet. Will keep you updated.

**Comment by axelboc** [comment] 2022-01-13 12:44
Yeah, `Toolbar` is a generic component used by each visualization's toolbar (the bar below the breadcrumbs). The "scalar" and "raw" visualizations are the only ones without a toolbar, which is why the issue doesn't appear when you open a scalar dataset.

Given what we've excluded so far, I'd be willing to bet that the issue comes from Angular's webpack config/version.

**Comment by wlievens** [comment] 2022-01-13 13:07
It does seem like Angular 13 imposes Webpack 5, and I agree with your analysis that the issue seems to be there.

What would be required to get h5web working with Webpack 4? I don't know how many Angular versions I'd have to go back to get to Webpack 4, I'll try to look into it ...

**Comment by axelboc** [comment] 2022-01-13 13:16
We're currently working on another round of upgrades, including CRA v5 for the demo, which includes webpack 5. That being said, if I understand the issue you linked to, it seems webpack 5 will uncover the issue above, not fix it, so may have to take the problem to `react-keyed-flatten-children`.

**Comment by wlievens** [comment] 2022-01-13 13:22
I fear I don't understand enough about how webpack and all the other "behind the scenes" mechanisms work to contribute something useful :-|

**Comment by wlievens** [comment] 2022-01-17 14:06
I'm getting this funky error when I build the application:

```
./node_modules/@h5web/app/dist/index.js:1:0 - Error: Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
You may need an additional loader to handle the result of these loaders.
> import _asyncToGenerator from "C:\\....\\asyncToGenerator.js";
| var __defProp = Object.defineProperty;
| var __defProps = Object.defineProperties;
```
I have no idea what it's about, I'll try and google my way out.

**Comment by axelboc** [comment] 2022-01-17 14:11
Hmm yeah, okay. It's because I removed `"type": "module"` from the `package.json` of `@h5web/app`. I thought it might have helped, like it did for CRA v5, but clearly it didn't for your set-up. 😄 

As mentioned, I think the way forward would be for you to set up a minimal reproduction repository that we can play with.

**Comment by wlievens** [comment] 2022-01-17 15:15
I created a minimal Angular project with a wrapper for h5web using the `MockProvider`.

It's the **example** project here:

https://github.com/wlievens/h5web-issue-914

Instructions in the README in the example dir should be enough.

**Comment by wlievens** [comment] 2022-01-20 09:16
Hey, have you had time to try and reproduce the issue?

**Comment by axelboc** [comment] 2022-01-20 15:39
I've managed to make it work, sorry for the wait. I've released the fix in a beta version: `v1.4.1-beta.2`. Let me know how you go.

After the PR above, #940, which did not fix the issue, I tried bundling `react-keyed-flatten-children` inside `@h5web/lib` as a last resort. I'm filtering it out of the `externals` configuration that we pass to Rollup when building the library: https://github.com/silx-kit/h5web/commit/5cf8015953e43061ab1721ff5e9a9833c5d0f136

**Comment by axelboc** [comment] 2022-01-20 15:52
I'm still not convinced the problem comes from the `react-keyed-flatten-children` package. It provides a simple CommonJS bundle with a default function export: `exports.default = flattenChildren` -- nothing crazy -- so I feel like this should be supported by Angular/webpack 5.

Regardless, I've opened an issue https://github.com/grrowl/react-keyed-flatten-children/issues/3 to suggest providing an ESM build.

**Comment by wlievens** [comment] 2022-01-20 15:55
I tested your new build and this works! I don't understand where the issue comes from either but I'm not very knowledgeable on how various kinds of bundles and imports in JS work, but I'm happy of course it works like this now.

**Closed** 2022-01-25 09:26 UTC

**Comment by axelboc** [comment] 2023-09-12 11:29
Hi @wlievens, `react-keyed-flatten-children` [now has an ESM bundle](https://github.com/grrowl/react-keyed-flatten-children/blob/master/CHANGELOG.md), so I've reverted the workaround that consisted in inlining it in the lib's output bundle (cf. https://github.com/silx-kit/h5web/issues/914).

It will go out in the next major release, along with the React 18 upgrade. Please do get back to us then, if the error comes back.
