### ISSUE TITLE
Axis not positioned properly relative to the Mesh

### ISSUE THREAD

**Issue by dmitrie-ai** [silx-kit/h5web#742] opened 2021-07-06 13:54 UTC
![image](https://user-images.githubusercontent.com/72915468/124611695-96ed5280-de69-11eb-9b71-f34014b6f0ac.png)

The Mesh is not positioned correctly in the Axis.
The Heatmap in the example is 100x100 yet on the horizontal axis the graph goes up to ~120 and there is a gap on the left. This happens with Lines as well as Heatmaps.

**Comment by axelboc** [comment] 2021-07-06 14:32
Hi @dmitrie-ai, this is very strange. It looks like the ordinate is all stretched out somehow, which is probably what leads to the mesh not being aligned and sized properly.

Would you mind providing us with a bit more details on how you got this point?

- Are you running H5Web in JupyterLab with the `jupyterlab_h5web` extension?
- If so, is it via the ESRF's jupyter-slurm service or on your own machine/environment?
- If on your own machine/environment, which versions of JupyerLab and the `jupyterlab_h5web` extension are you running?
- Are you using the `H5Web` python widget in a notebook, or are you opening an HDF5 file in a separate tab?
- Which browser and version are you using?
- Have you changed some settings in Jupyter Lab or your browser, like the font size, zoom level, etc.?
- Are you applying extra CSS somehow that could conflict with H5Web's own CSS?
- Is there any chance you could provide us with a reproduction environment, perhaps a Binder?

**Comment by dmitrie-ai** [comment] 2021-07-06 14:48
Hi @axelboc, I am just running the example at https://h5web.panosc.eu/hsds?file=/home/reader/links after having observed the same behavior when working with h5web/lib on my own device. The web browser is Chrome Version 91.0.4472.114 (Official Build) (64-bit).
I haven't made any changes at all.

Thank you

**Comment by dmitrie-ai** [comment] 2021-07-06 14:50
Just tried on Firefox and the problem is gone. Must be an issue with Chrome.

**Comment by axelboc** [comment] 2021-07-06 15:05
Awesome, thanks, we'll investigate.

**Comment by axelboc** [comment] 2021-07-07 06:56
Hmm, we can't seem to replicate the bug in Chrome 91 on our end. Which OS are you on? Is your browser at the default zoom level of 100%? Have you changed any settings like default font size, etc.?

**Comment by dmitrie-ai** [comment] 2021-07-07 13:18
I reset my Chrome settings to default  zoom level is at 100%. The issue still persists. 
OS info:
Edition	Windows 10 Home
Version	20H2
OS build	19042.1052
Experience   Windows Feature Experience Pack 120.2212.2020.0

btw, the exact link I opened is 
https://h5web.panosc.eu/hsds?file=/home/reader/links

**Comment by axelboc** [comment] 2021-07-07 14:58
Could it be a browser extension (e.g. ad blocker) messing up with the HTML/CSS of the page, somehow?

**Comment by dmitrie-ai** [comment] 2021-07-07 15:22
Since I reset Chrome to default, all the extensions have been disabled

**Comment by axelboc** [comment] 2021-07-08 12:57
- Does Chrome's reset feature clear the cache? Could be some cached CSS interfering. 🤷 
- I gather from the screenshot that you have enabled Windows' dark mode? Maybe try disabling it and restarting Chrome.
- Does the issue appear in Microsoft Edge v91 as well? (It uses the same rendering engine as Chrome.)
- Do you have access to another Chrome installation? Does the issue appear there as well?
- Last resort, you could try reinstalling Chrome completely.

**Comment by dmitrie-ai** [comment] 2021-07-08 13:04
I cleared all data and disabled dark mode. The issue still persists in Chrome and Edge. I will try it on a Linux machine when I get the chance.
Since It displays properly in Firefox, this issue isn't crucial, perhaps Chrome will release an update of some sorts and it will fix it.
Thank you for your time

**Comment by axelboc** [comment] 2021-07-08 13:29
Oh maybe this has something to do with your device's pixel ratio. Are you on a retina device?

Sorry for all the dead ends... I'm sure we'll get to the bottom of this 😁

**Comment by dmitrie-ai** [comment] 2021-07-08 14:40
I checked window.devicePixelRatio both in Firefox and Chrome console and they both output 1.25. I am not using a Retina device.
No worries at all, this is looking like a deep rabbit hole. It would be satisfying to find out why it doesn't display properly, but the issue doesn't bother me since the main browser we use is Firefox. I would be fine with ignoring it before it takes up too much of your time

**Comment by axelboc** [comment] 2021-07-08 14:51
Alright, let's close the issue for now then. The problem could come from Three.JS or `react-three-fiber`, in which case a future update might fix it. If anything changes, please let us know. 😉 If anyone else experiences the same issue, let us know as well and we'll re-open the issue.

**Closed by axelboc** 2021-07-08 14:51 UTC
